---
# a role that sets up an environment for developing the hub on a ubuntu machine
# it assumes the role `ubuntu-build` has been applied
- name: enable github deploy access
  become: true
  become_user: "{{build_user}}"
  file:
    dest: "/home/{{build_user}}/.ssh"
    mode: "0700"
    owner: "{{build_user}}"
    group: "{{build_user}}"
    state: directory
  tags: gitco

- name: enable github deploy access
  become: true
  become_user: "{{build_user}}"
  copy:
    src: github_deploy_rsa
    dest: "/home/{{build_user}}/.ssh/id_rsa"
    mode: "0600"
    owner: "{{build_user}}"
    group: "{{build_user}}"
  tags: gitco

- name: checkout hub sources
  git:
    repo: "git@github.com:tomster/nuimo-hub-backend"
    remote: tomster
    dest: "/home/{{build_user}}/nuimo-hub-backend"
    version: "wifi-onboarding"
    accept_hostkey: true
  become: true
  become_user: "{{build_user}}"
  tags:
    - gitco
    - gitup

- name: bootstrap development checkout
  become: true
  become_user: "{{build_user}}"
  command: make
  args:
    creates: "/home/{{build_user}}/nuimo-hub-backend/application/venv/bin/python"
    chdir: "/home/{{build_user}}/nuimo-hub-backend/application/"
  tags: gitco
