---
- name: create application group
  become: true
  group:
    name: "{{run_user}}"

- name: create application user
  become: true
  user:
    name: "{{run_user}}"
    group: "{{run_user}}"
    createhome: yes
    shell: /bin/sh

- name: create deploy user
  become: true
  user:
    name: "{{deploy_user}}"
    groups: "{{run_user}}"
    append: yes
    createhome: yes
    shell: /bin/sh

- name: create deployment location
  become: true
  file:
    dest: "{{deploy_location}}"
    owner: "{{deploy_user}}"
    group: "{{run_user}}"
    mode: "0755"
    state: directory

- name: create data location
  become: true
  file:
    dest: "{{data_location}}"
    owner: "{{run_user}}"
    group: "{{run_user}}"
    mode: "0750"
    state: directory

- name: init virtualenv in deployment location
  command: "{{python_interpreter}} -m venv venv"
  args:
    chdir: "{{deploy_location}}"
    creates: "{{deploy_location}}/venv/bin/python"

- name: upload python requirements
  become: true
  copy:
    dest: "{{deploy_location}}/requirements.txt"
    owner: "{{deploy_user}}"
    group: "{{run_user}}"
    mode: "0644"
    content: |
      pip==9.0.1
      click==6.6
      colander==1.3.1
      cornice==1.2.1
      iso8601==0.1.11
      PasteDeploy==1.5.2
      pyramid==1.7.3
      pytz==2016.10
      repoze.lru==0.6
      requests==2.12.4
      simplejson==3.10.0
      translationstring==1.3
      venusian==1.0
      WebOb==1.7.0rc2
      zope.deprecation==4.2.0
      zope.interface==4.3.3
      senic.nuimo-hub

- name: install application
  pip:
    virtualenv: "{{deploy_location}}/venv/"
    requirements: "{{deploy_location}}/requirements.txt"
    extra_args: "--pre --upgrade -i {{devpi_index_url}}"
  # notify: restart backend
  tags: update_backend

