git:
  depth: 10000
sudo: required
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/senic_hub/frontend/node_modules/
    - $HOME/nodejs
python:
- '3.5'
env:
  global:
  - LINUX_WITHOUT_DBUS=1
  - devpi_user=travis
before_install:
  - "./travis_before_install.sh"
install:
  - pip install tox-travis
script: tox
after_success:
- "./travis_after_success.sh"
notifications:
  slack:
    secure: ZmW+YVhsA4/KTWtv8lOUkaKRkE+gGOWkgTsBni0KZLqzS1AHzV3+oxi3HWmleQwPQmISzDAlifsHayKAvLVqz67agw5aMLY2oza2xJMeghZxae7CGdQvPgoLvnj3e0pjXtBU6/cyxSbIhJHyu22oBbHqGJasPUqRsCDEnnbA6QgmtyX7F6KLQOUFBg/degdDQZDv0IV5p1Q6R/Vig85tE3gizG3AmRXDKuWAjsjBEGc2LIJhhlGd6zeByyFXJxwB+ERsFlFYvj2RgI2LoYQYOsKwJpEPk37EIzRHhr7QWHu0eTzbTWhv54ih5FYDuuQTsSbabuxLwDiKtCMkBdPVeLqAhFahrw4H5QruZpWX86b/1e+idxGEybY8BB9HkzFDP5rIhB1KLVLZg/0PQFz4z4K4ek48Dyivuzsynmvxo4uEizfsejd8XiHzerbOdkPQKfzKS+sfFzBoIG2yITDBHrS1zVBCdu54kP30BfUiik80aXE+zY7EJXYKE/Qb6yAO+H1OENE4ht/LMEee1z1hv9Ua6e5GHBBTGP+fkIjEhjCozGXWlOrBnRVd3mcTuGPhjqABg9ZwwXo3/cGcH8yl4az7EY4e7Vs4K8qCK2xbAHG4qs3rd2DIyAVghDJHExCiwMRXfYDiKAooJQoZjY+wNZklPyb2Zt/yJgDOTrfAolk=
