---
- name: disable stock bluez (it's too old)
  apt:
    name: "{{item}}"
    state: absent
  with_items:
    - bluez

- name: install build dependencies
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - git-core
    - libusb-dev
    - libdbus-1-dev
    - libglib2.0-dev
    - libudev-dev
    - libical-dev
    - libreadline-dev
    - libdbus-glib-1-dev
    - unzip

- name: create build user
  become: true
  user:
    name: "{{build_user}}"
    createhome: yes
    shell: /bin/bash
    # set password to '*' to unlock ssh access
    password: $6$loHAn4IfYLEdMc$e0de/845DozoVAzG1rKx8eRqrBxRLnYJO746dqozpxYhxSgCfA7bI9p0KoDqNU8A0hot1zqJvMQNWM1IuJGnx1
    update_password: always
    groups: sudo
    append: yes

- name: ensure src directory exists
  file:
    dest: "{{src_dest}}"
    owner: "{{build_user}}"
    mode: "0755"
    state: directory

- name: upload custom bluez sources
  copy:
    src: "{{item}}" 
    dest: "{{src_dest}}/"
  with_items:
    - "bluez-{{bluez_version}}.tar.xz"  # http://www.kernel.org/pub/linux/bluetooth/bluez-5.43.tar.xz
  tags: bluez

- name: unpack custom bluez sources
  command: "tar xf bluez-{{bluez_version}}.tar.xz"
  args:
    chdir: "{{src_dest}}" 
    creates: "{{build_dir}}/README"
  tags: bluez
  become: true
  become_user: "{{build_user}}"

- name: upload pi3 patches
  copy:
    src: "{{item}}" 
    dest: "{{src_dest}}/"
  with_items:
    - 3b07a1eb296862da889609a84f8e10b299b7442d.zip  # https://gist.github.com/pelwell/c8230c48ea24698527cd/archive/3b07a1eb296862da889609a84f8e10b299b7442d.zip
  tags: bluez
  when: apply_pi3_patches

- name: unpack patch
  command: "unzip {{src_dest}}3b07a1eb296862da889609a84f8e10b299b7442d.zip"
  args:
    chdir: "{{build_dir}}"
    creates: "{{build_dir}}/c8230c48ea24698527cd-3b07a1eb296862da889609a84f8e10b299b7442d/0004-Move-the-43xx-firmware-into-lib-firmware.patch"
  tags: bluez
  become: true
  become_user: "{{build_user}}"
  when: apply_pi3_patches

- stat:
    path: "{{build_dir}}/c8230c48ea24698527cd-3b07a1eb296862da889609a84f8e10b299b7442d/0004-Move-the-43xx-firmware-into-lib-firmware.patch"
  register: bluez_patchfiles
  tags: bluez

- name: patch sources
  command: "git apply -v c8230c48ea24698527cd-3b07a1eb296862da889609a84f8e10b299b7442d/*"
  args:
    chdir: "{{build_dir}}"
  when: bluez_patchfiles.stat.exists == True
  tags: bluez
  become: true
  become_user: "{{build_user}}"

- name: clean up patches
  shell: "rm {{build_dir}}/c8230c48ea24698527cd-3b07a1eb296862da889609a84f8e10b299b7442d/*"
  args:
    removes: "{{build_dir}}/c8230c48ea24698527cd-3b07a1eb296862da889609a84f8e10b299b7442d/0004-Move-the-43xx-firmware-into-lib-firmware.patch"
  tags: bluez
  become: true
  become_user: "{{build_user}}"

- name: configure sources
  command: ./configure --prefix=/usr --mandir=/usr/share/man --sysconfdir=/etc --localstatedir=/var
  args:
    chdir: "{{build_dir}}"
    creates: "{{build_dir}}/config.log"
  tags: bluez
  become: true
  become_user: "{{build_user}}"

- name: compile sources
  command: make
  args:
    chdir: "{{build_dir}}"
    creates: "{{build_dir}}/client/bluetoothctl"
  tags: bluez
  become: true
  become_user: "{{build_user}}"

- stat:
    path: "{{build_dir}}/client/bluetoothctl"
  register: bluez_binary
  tags: bluez

- name: install sources
  command: make install
  args:
    chdir: "{{build_dir}}"
    creates: /usr/bin/bluetoothctl
  tags: bluez
  when: bluez_binary.stat.exists == True
