---
- name: disable stock bluez (it's too old)
  service:
    name: bluetooth
    state: stopped
    enabled: no
  tags: bluez

- name: install runtime dependencies
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - python3-dev
    - python3-gi
    - python3-dbus
    - supervisor

- include: from_src.yml
  tags: bluez

- name: create firmware directory
  file:
    dest: /etc/firmware
    state: directory
    owner: root
    group: root
    mode: 755
  tags: bluez
  when: upload_pi3_driver

- name: upload broadcomm driver
  copy:
    src: BCM43430A1.hcd  # https://github.com/OpenELEC/misc-firmware/raw/master/firmware/brcm/BCM43430A1.hcd
    dest: /lib/firmware/BCM43430A1.hcd
  tags: bluez
  when: upload_pi3_driver

- stat:
    path: /lib/firmware/BCM43430A1.hcd
  register: broadcomm_driver_exists
  tags: bluez


- name: install broadcomm driver
  file:
    src: /lib/firmware/BCM43430A1.hcd
    dest: /etc/BCM43430A1.hcd
    state: link
  tags: bluez
  when: broadcomm_driver_exists.stat.exists == True

- name: configure supervisor to manage bluetoothd
  template:
    src: bluetoothd_supervisor.conf
    dest: /etc/supervisor/conf.d/bluetoothd.conf
    owner: root
    mode: "0644"
  notify: reload supervisord
  tags: supervisord

- name: ensure supervisord is running
  service:
    name: supervisor
    state: running
    enabled: yes
  tags: supervisord
