---
- name: disable stock bluez (it's too old)
  service:
    name: bluetooth
    state: stopped
    enabled: no
  tags: bluez

- name: install runtime dependencies
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - libusb-dev
    - libdbus-1-dev
    - libglib2.0-dev
    - libudev-dev
    - libical-dev
    - libreadline-dev
    - python-dev
    - libdbus-glib-1-dev
    - python-gi
    - python-pip
    - python-setuptools
    - supervisor

- name: install bluez (binary)
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - bluez
  when: not install_from_source
  tags: bluez

- include: from_src.yml
  when: install_from_source
  tags: bluez

- name: install dbus-python
  pip:
    name: dbus-python

- name: create firmware directory
  file:
    dest: /etc/firmware
    state: directory
    owner: root
    group: root
    mode: 755
  tags: bluez
  when: upload_pi3_driver

- name: upload broadcomm driver
  copy:
    src: BCM43430A1.hcd  # https://github.com/OpenELEC/misc-firmware/raw/master/firmware/brcm/BCM43430A1.hcd
    dest: /lib/firmware/BCM43430A1.hcd
  tags: bluez
  when: upload_pi3_driver

- name: install broadcomm driver
  file:
    src: /lib/firmware/BCM43430A1.hcd
    dest: /etc/BCM43430A1.hcd
    state: link
  tags: bluez

- name: upload hciattach script
  copy:
    src: hciattach.sh
    dest: /usr/local/bin/hciattach.sh
    mode: "0755"

- name: configure supervisor to manage bluetoothd
  template:
    src: bluetoothd_supervisor.conf
    dest: /etc/supervisor/conf.d/bluetoothd.conf
    owner: root
    mode: "0644"
  notify: reload supervisord
  tags: supervisord

- name: ensure supervisord is running
  service:
    name: supervisor
    state: running
    enabled: yes
  tags: supervisord