      homeassistant:
        name: {{ploy_hostname}}-{{ansible_machine_id[:4]}}
        latitude: 52.5155
        longitude: 13.4062
        elevation: 32
        # metric for Metric, imperial for Imperial
        unit_system: metric
        time_zone: Europe/Berlin

      # Enables the frontend
      frontend:

      http:
        # Uncomment this to add a password (recommended!)
        # api_password: PASSWORD
        # Uncomment this if you are using SSL or running in Docker etc
        # base_url: example.duckdns.org:8123

      # Checks for available updates
      updater:

      # Discover some devices automatically
      discovery:

      # Enables support for tracking state changes over time.
      history:

      # View all events in a logbook
      logbook:

      # Track the sun
      sun:

      # Weather Prediction
      sensor:
        platform: yr
