homeassistant:
  name: {{hostname}}
  latitude: 52.5155
  longitude: 13.4062
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: Europe/Berlin

http:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

media_player:
  - platform: sonos
    hosts: 192.168.1.42

light:
  platform: hue
  host: 192.168.1.83
