---
- name: set hostname
  hostname:
    name: "{{ploy_hostname}}"

- name: install runtime dependencies
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - python3.5
    - wpasupplicant
    - wireless-tools
    - supervisor
    - python3-venv
    - libffi-dev
    - libssl-dev

- name: configure network interfaces
  template:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    mode: "0644"
  notify: restart wlan
  tags: wlan
