---
- name: set hostname
  hostname:
    name: "{{ploy_hostname}}"

- name: install runtime dependencies
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - avahi-daemon
    - python3.5
    - wpasupplicant
    - wireless-tools
    - supervisor
    - python3-venv
    - libffi-dev
    - libssl-dev
    - lighttpd

- name: configure network interfaces
  template:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    mode: "0644"
  notify: restart wlan
  tags: wlan

- name: ensure document root
  file:
    dest: "{{frontend_document_root}}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  tags: www

- name: configure lighttpd
  template:
    src: lighttpd.conf
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart httpd
  tags: www

- name: configure frontend website
  template:
    src: nuimo_hub.conf
    dest: /etc/lighttpd/conf-available/nuimo_hub.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart httpd
  tags: www

- name: enable frontend website
  file:  
    src: /etc/lighttpd/conf-available/nuimo_hub.conf
    dest: /etc/lighttpd/conf-enabled/nuimo_hub.conf
    owner: root
    group: root
    mode: "0755"
    state: link
  notify: restart httpd
  tags: www

- name: announce web UI via avahi
  template:
    src: hub_service.xml
    dest: /etc/avahi/services/hub.service
    owner: root
    mode: "0644"
  notify: restart avahi
  tags: avahi
