---
- name: restart wlan
  raw: ifdown wlan0 && ifup wlan0
  args:
    executable: /bin/bash

- name: restart avahi
  service:
    name: avahi-daemon
    state: restarted

- name: restart httpd
  service:
    name: lighttpd
    state: restarted
