swagger: '2.0'

info:
  version: "1.0.0"
  title: senic.nuimo_hub API
basePath: /-
paths:
  /:
    get:
      description: |
        The main entry point for all clients.
      responses:
        200:
          description: Returns all entry points and other information for bootstrapping clients.
          schema:
            title: General information about the application
            type: object
            properties:
              version:
                type: string
                description: |
                  The version deployed, use this when referencing behaviour in tickets etc.
